# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0026_event_series_not_mandatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Series'},
        ),
    ]
